In [1]:
import DataCleaning
import Transformation
allBitcoinData = DataCleaning.getBitcoinData()

/Users/shivasaravanan/CryptoDataFull/DataCleaning.py:140: DtypeWarning: Columns (83,87,88,91) have mixed types. Specify dtype option on import or set low_memory=False.
  bitcoinPosts = pd.read_csv("bitcoin_posts.csv")[["normal_date", "one"]]
/Users/shivasaravanan/CryptoDataFull/DataCleaning.py:153: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bitcoinModTrends["DayTime"] = pd.to_datetime(bitcoinModTrends["Day"])


In [2]:
import statsmodels.api as sm
import pandas as pd

In [25]:
X = sm.add_constant(allBitcoinData[['transactions_float', 'tweet_count', 'trends_float', "posts_float"]])
Y = allBitcoinData["Close"]
lognormal_model = sm.GLM(Y, X, family=sm.families.InverseGaussian())
lognormal_results = lognormal_model.fit()
print(lognormal_results.summary())

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/statsmodels/genmod/families/links.py:318: RuntimeWarning: invalid value encountered in power
  return np.power(z, 1. / self.power)


ValueError: NaN, inf or invalid value detected in weights, estimation infeasible.

In [16]:
trX = sm.add_constant(Transformation.repeated_gs_removal(["posts_float", "tweet_count", "trends_float"], ["transactions_float"], allBitcoinData))                                                                                                                                    
                                       

[[4.26953189e-02 3.90000000e+01]
 [4.95006088e-02 2.20000000e+01]
 [4.88004132e-02 3.20000000e+01]
 ...
 [3.26920588e-02 1.38000000e+02]
 [3.13188093e-02 1.35000000e+02]
 [4.01812296e-02 1.65000000e+02]]
[[ 0.04269532 -0.04631728]
 [ 0.04950061 -0.05969788]
 [ 0.04880041 -0.05618951]
 ...
 [ 0.03269206 -0.00752779]
 [ 0.03131881 -0.00648902]
 [ 0.04018123 -0.01044414]]
[[ 0.04269532 -0.04631728]
 [ 0.04950061 -0.05969788]
 [ 0.04880041 -0.05618951]
 ...
 [ 0.03269206 -0.00752779]
 [ 0.03131881 -0.00648902]
 [ 0.04018123 -0.01044414]]
[[4.26953189e-02 5.30000000e+01]
 [4.95006088e-02 8.60000000e+01]
 [4.88004132e-02 7.80000000e+01]
 ...
 [3.26920588e-02 2.49000000e+02]
 [3.13188093e-02 2.40000000e+02]
 [4.01812296e-02 5.90000000e+02]]
[[ 0.04269532 -0.04930771]
 [ 0.04950061 -0.05240807]
 [ 0.04880041 -0.05298158]
 ...
 [ 0.03269206  0.00264184]
 [ 0.03131881  0.00281374]
 [ 0.04018123  0.05828599]]
[[ 0.04269532 -0.04930771]
 [ 0.04950061 -0.05240807]
 [ 0.04880041 -0.05298158]
 ...
 [

In [17]:
idx = pd.date_range('2020-08-02', '2022-02-28')
X = trX
X.index = idx
Y = allBitcoinData["standardized_price"]
X

const  posts_float  tweet_count  trends_float
2020-08-02    1.0    -0.046317    -0.049308     -0.031037
2020-08-03    1.0    -0.059698    -0.052408     -0.048649
2020-08-04    1.0    -0.056190    -0.052982     -0.049824
2020-08-05    1.0    -0.044507    -0.041983     -0.041090
2020-08-06    1.0    -0.055134    -0.054619     -0.054013
...           ...          ...          ...           ...
2022-02-24    1.0    -0.000182     0.068155      0.100102
2022-02-25    1.0    -0.007597     0.045551      0.041599
2022-02-26    1.0    -0.007528     0.002642      0.032710
2022-02-27    1.0    -0.006489     0.002814      0.032600
2022-02-28    1.0    -0.010444     0.058286      0.036835

[576 rows x 4 columns]

In [19]:
lognormal_model = sm.GLM(Y, X, family=sm.families.Gaussian(sm.families.links.log()))

In [20]:
lognormal_results = lognormal_model.fit()

In [21]:
print(lognormal_results.summary())

                 Generalized Linear Model Regression Results                  
Dep. Variable:     standardized_price   No. Observations:                  576
Model:                            GLM   Df Residuals:                      572
Model Family:                Gaussian   Df Model:                            3
Link Function:                    log   Scale:                         0.96806
Method:                          IRLS   Log-Likelihood:                -805.96
Date:                Tue, 05 Apr 2022   Deviance:                       553.73
Time:                        11:11:37   Pearson chi2:                     554.
No. Iterations:                   100   Pseudo R-squ. (CS):            0.03915
Covariance Type:            nonrobust                                         
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
const           -1.2479      0.310     -4.022   

In [9]:
postX = Transformation.repeated_gs_removal(["standardized_txs", "standardized_tweets", "standardized_trends"], ["standardized_posts"], allBitcoinData)
postX["constant"] = 1        

[[-0.05348455  0.23409743]
 [-0.05838202  1.24468037]
 [-0.05550116  1.1407016 ]
 ...
 [-0.02496399 -1.25138285]
 [-0.02582825 -1.45530987]
 [-0.01718566 -0.13924385]]
[[-0.05348455 -0.0108876 ]
 [-0.05838202  0.03250454]
 [-0.05550116  0.02899068]
 ...
 [-0.02496399 -0.06614243]
 [-0.02582825 -0.07563958]
 [-0.01718566 -0.01312272]]
[[-0.05348455 -0.0108876 ]
 [-0.05838202  0.03250454]
 [-0.05550116  0.02899068]
 ...
 [-0.02496399 -0.06614243]
 [-0.02582825 -0.07563958]
 [-0.01718566 -0.01312272]]
[[-0.05348455 -1.23736233]
 [-0.05838202 -1.07647839]
 [-0.05550116 -1.11548056]
 ...
 [-0.02496399 -0.28180927]
 [-0.02582825 -0.3256867 ]
 [-0.01718566  1.38065805]]
[[-0.05348455 -0.02410176]
 [-0.05838202 -0.01195728]
 [-0.05550116 -0.01618903]
 ...
 [-0.02496399  0.00422959]
 [-0.02582825  0.00259006]
 [-0.01718566  0.08533237]]
[[-0.05348455 -0.02410176]
 [-0.05838202 -0.01195728]
 [-0.05550116 -0.01618903]
 ...
 [-0.02496399  0.00422959]
 [-0.02582825  0.00259006]
 [-0.01718566  0.085

In [10]:
X = postX
X.index = idx
Y = allBitcoinData["Close"]
X

standardized_txs  standardized_tweets  standardized_trends  \
2020-08-02         -0.010888            -0.024102            -0.009467   
2020-08-03          0.032505            -0.011957            -0.014948   
2020-08-04          0.028991            -0.016189            -0.018834   
2020-08-05         -0.005836            -0.015574            -0.021068   
2020-08-06          0.059131            -0.016306            -0.019547   
...                      ...                  ...                  ...   
2022-02-24         -0.026596             0.087840             0.109300   
2022-02-25         -0.023232             0.065026             0.048161   
2022-02-26         -0.066142             0.004230             0.031529   
2022-02-27         -0.075640             0.002590             0.029352   
2022-02-28         -0.013123             0.085332             0.045983   

            constant  
2020-08-02         1  
2020-08-03         1  
2020-08-04         1  
2020-08-05         1  
2020-08-06         1  
...              ...  
2022-02-24         1  
2022-02-25         1  
2022-02-26         1  
2022-02-27         1  
2022-02-28         1  

[576 rows x 4 columns]

In [11]:
lognormal_model = sm.GLM(Y, X, family=sm.families.Gaussian())
lognormal_results = lognormal_model.fit()
print(lognormal_results.summary())

                 Generalized Linear Model Regression Results                  
Dep. Variable:                  Close   No. Observations:                  576
Model:                            GLM   Df Residuals:                      572
Model Family:                Gaussian   Df Model:                            3
Link Function:               identity   Scale:                      2.4180e+08
Method:                          IRLS   Log-Likelihood:                -6374.7
Date:                Tue, 05 Apr 2022   Deviance:                   1.3831e+11
Time:                        11:09:25   Pearson chi2:                 1.38e+11
No. Iterations:                     3   Pseudo R-squ. (CS):             0.1126
Covariance Type:            nonrobust                                         
                          coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------------
standardized_txs    -4.204e+04    

In [12]:
trendX = Transformation.repeated_gs_removal(["standardized_txs", "standardized_tweets", "standardized_posts"], ["standardized_trends"], allBitcoinData)
trendX["constant"] = 1   
X = trendX
X.index = idx
Y = allBitcoinData["standardized_price"]
X

[[-0.03081117  0.23409743]
 [-0.03783051  1.24468037]
 [-0.04017029  1.1407016 ]
 ...
 [ 0.01832422 -1.25138285]
 [ 0.01598444 -1.45530987]
 [ 0.03470268 -0.13924385]]
[[-0.03081117  0.01086396]
 [-0.03783051  0.05325002]
 [-0.04017029  0.04899861]
 ...
 [ 0.01832422 -0.05283076]
 [ 0.01598444 -0.06124936]
 [ 0.03470268 -0.00704859]]
[[-0.03081117  0.01086396]
 [-0.03783051  0.05325002]
 [-0.04017029  0.04899861]
 ...
 [ 0.01832422 -0.05283076]
 [ 0.01598444 -0.06124936]
 [ 0.03470268 -0.00704859]]
[[-0.03081117 -1.23736233]
 [-0.03783051 -1.07647839]
 [-0.04017029 -1.11548056]
 ...
 [ 0.01832422 -0.28180927]
 [ 0.01598444 -0.3256867 ]
 [ 0.03470268  1.38065805]]
[[-0.03081117 -0.04178218]
 [-0.03783051 -0.02602031]
 [-0.04017029 -0.02605511]
 ...
 [ 0.01832422 -0.03325722]
 [ 0.01598444 -0.03357038]
 [ 0.03470268  0.04631793]]
[[-0.03081117 -0.04178218]
 [-0.03783051 -0.02602031]
 [-0.04017029 -0.02605511]
 ...
 [ 0.01832422 -0.03325722]
 [ 0.01598444 -0.03357038]
 [ 0.03470268  0.046

standardized_txs  standardized_tweets  standardized_posts  \
2020-08-02          0.010864            -0.041782           -0.044731   
2020-08-03          0.053250            -0.026020           -0.046912   
2020-08-04          0.048999            -0.026055           -0.042678   
2020-08-05          0.014822            -0.021323           -0.037295   
2020-08-06          0.074241            -0.022402           -0.035829   
...                      ...                  ...                 ...   
2022-02-24         -0.024636            -0.001489           -0.053923   
2022-02-25         -0.016846             0.022692           -0.034838   
2022-02-26         -0.052831            -0.033257           -0.035798   
2022-02-27         -0.061249            -0.033570           -0.035681   
2022-02-28         -0.007049             0.046318           -0.034721   

            constant  
2020-08-02         1  
2020-08-03         1  
2020-08-04         1  
2020-08-05         1  
2020-08-06         1  
...              ...  
2022-02-24         1  
2022-02-25         1  
2022-02-26         1  
2022-02-27         1  
2022-02-28         1  

[576 rows x 4 columns]

In [13]:
lognormal_model = sm.GLM(Y, X, family=sm.families.Gaussian())
lognormal_results = lognormal_model.fit()
print(lognormal_results.summary())

                 Generalized Linear Model Regression Results                  
Dep. Variable:     standardized_price   No. Observations:                  576
Model:                            GLM   Df Residuals:                      572
Model Family:                Gaussian   Df Model:                            3
Link Function:               identity   Scale:                         0.81107
Method:                          IRLS   Log-Likelihood:                -754.99
Date:                Tue, 05 Apr 2022   Deviance:                       463.93
Time:                        11:09:25   Pearson chi2:                     464.
No. Iterations:                     3   Pseudo R-squ. (CS):             0.2133
Covariance Type:            nonrobust                                         
                          coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------------
standardized_txs       -2.7591    

In [14]:
tweetX = Transformation.repeated_gs_removal(["standardized_txs", "standardized_trends", "standardized_posts"], ["standardized_tweets"], allBitcoinData)
tweetX["constant"] = 1   
X = tweetX
X.index = idx
Y = allBitcoinData["standardized_price"]
X

[[-0.05155676  0.23409743]
 [-0.04485327  1.24468037]
 [-0.04647836  1.1407016 ]
 ...
 [-0.01174205 -1.25138285]
 [-0.01357028 -1.45530987]
 [ 0.05752742 -0.13924385]]
[[-0.05155676  0.00543946]
 [-0.04485327  0.04826214]
 [-0.04647836  0.04377721]
 ...
 [-0.01174205 -0.05331669]
 [-0.01357028 -0.06199806]
 [ 0.05752742 -0.00096951]]
[[-0.05155676  0.00543946]
 [-0.04485327  0.04826214]
 [-0.04647836  0.04377721]
 ...
 [-0.01174205 -0.05331669]
 [-0.01357028 -0.06199806]
 [ 0.05752742 -0.00096951]]
[[-0.05155676 -0.73946811]
 [-0.04485327 -0.9079323 ]
 [-0.04647836 -0.96408703]
 ...
 [-0.01174205  0.43978123]
 [-0.01357028  0.3836265 ]
 [ 0.05752742  0.83286434]]
[[-0.05155676  0.00608101]
 [-0.04485327 -0.00981776]
 [-0.04647836 -0.01150147]
 ...
 [-0.01174205  0.03611016]
 [-0.01357028  0.03461676]
 [ 0.05752742 -0.00634215]]
[[-0.05155676  0.00608101]
 [-0.04485327 -0.00981776]
 [-0.04647836 -0.01150147]
 ...
 [-0.01174205  0.03611016]
 [-0.01357028  0.03461676]
 [ 0.05752742 -0.006

standardized_txs  standardized_trends  standardized_posts  \
2020-08-02          0.005439             0.006081           -0.027989   
2020-08-03          0.048262            -0.009818           -0.039238   
2020-08-04          0.043777            -0.011501           -0.034384   
2020-08-05          0.009792            -0.014737           -0.030857   
2020-08-06          0.069537            -0.012292           -0.028579   
...                      ...                  ...                 ...   
2022-02-24         -0.015857             0.070738           -0.060652   
2022-02-25         -0.012031             0.011518           -0.052349   
2022-02-26         -0.053317             0.036110           -0.022432   
2022-02-27         -0.061998             0.034617           -0.022128   
2022-02-28         -0.000970            -0.006342           -0.065327   

            constant  
2020-08-02         1  
2020-08-03         1  
2020-08-04         1  
2020-08-05         1  
2020-08-06         1  
...              ...  
2022-02-24         1  
2022-02-25         1  
2022-02-26         1  
2022-02-27         1  
2022-02-28         1  

[576 rows x 4 columns]

In [15]:
lognormal_model = sm.GLM(Y, X, family=sm.families.Gaussian())
lognormal_results = lognormal_model.fit()
print(lognormal_results.summary())

                 Generalized Linear Model Regression Results                  
Dep. Variable:     standardized_price   No. Observations:                  576
Model:                            GLM   Df Residuals:                      572
Model Family:                Gaussian   Df Model:                            3
Link Function:               identity   Scale:                         0.77818
Method:                          IRLS   Log-Likelihood:                -743.07
Date:                Tue, 05 Apr 2022   Deviance:                       445.12
Time:                        11:09:25   Pearson chi2:                     445.
No. Iterations:                     3   Pseudo R-squ. (CS):             0.2532
Covariance Type:            nonrobust                                         
                          coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------------
standardized_txs       -2.7511    